# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimagen.proto\x12\x0fprotocolBuffers\"\xdd\x01\n\nVideoFrame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x12/\n\x08\x65ncoding\x18\x05 \x01(\x0e\x32\x1d.protocolBuffers.EncodingType\x12\x14\n\x0c\x66rame_number\x18\x06 \x01(\x03\x12\x11\n\ttimestamp\x18\x07 \x01(\x01\x12\x1b\n\x13\x63ompression_quality\x18\x08 \x01(\x05\x12\x13\n\x0bis_keyframe\x18\t \x01(\x08*4\n\x0c\x45ncodingType\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04JPEG\x10\x01\x12\x07\n\x03LZ4\x10\x02\x12\x07\n\x03PNG\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imagen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENCODINGTYPE._serialized_start=257
  _ENCODINGTYPE._serialized_end=309
  _VIDEOFRAME._serialized_start=34
  _VIDEOFRAME._serialized_end=255
# @@protoc_insertion_point(module_scope)
