# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/trinocular.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages import imagen_pb2 as messages_dot_imagen__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19messages/trinocular.proto\x12\x0fprotocolBuffers\x1a\x15messages/imagen.proto\"\x96\x01\n\x10TripleVideoFrame\x12)\n\x04left\x18\x01 \x01(\x0b\x32\x1b.protocolBuffers.VideoFrame\x12+\n\x06\x63\x65nter\x18\x02 \x01(\x0b\x32\x1b.protocolBuffers.VideoFrame\x12*\n\x05right\x18\x03 \x01(\x0b\x32\x1b.protocolBuffers.VideoFrameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.trinocular_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRIPLEVIDEOFRAME']._serialized_start=70
  _globals['_TRIPLEVIDEOFRAME']._serialized_end=220
# @@protoc_insertion_point(module_scope)
